name: "Test code"
on:
  pull_request:

  workflow_dispatch:
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checking out code'
        uses: actions/checkout@v2
      - name: 'Installing node'
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install Dependencies using yarn
        run: yarn install
      - name: Run tests with yarn
        run: yarn test